Compiling source
	intg_tests/dataproviders:0.0.0
WARNING [tests/new-data-provider-tests.bal:(121:9,121:21)] unused variable 'a'
WARNING [tests/new-data-provider-tests.bal:(153:9,153:21)] unused variable 'a'

Running Tests with Coverage

	dataproviders
	[fail] [before test function for the test]:
	    error("{ballerina}DivisionByZero",message=" / by zero")
			callableName: beforeFailsFunction moduleName: intg_tests.dataproviders$test.0.tests.new-data-provider-tests fileName: tests/new-data-provider-tests.bal lineNumber: 121
			callableName: beforeFailsFunction$lambda55$ moduleName: intg_tests.dataproviders$test.0.tests.new-data-provider-tests fileName: tests/new-data-provider-tests.bal lineNumber: 127
			callableName: call moduleName: ballerina.lang.function.0 fileName: function.bal lineNumber: 37
			callableName: executeFunction moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 142
			callableName: executeBeforeFunction moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 121
			callableName: prepareDataDrivenTest moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 102
			callableName: executeDataDrivenTestSet moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 63
			callableName: executeTest moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 28
			callableName: executeTests moduleName: ballerina.test.0 fileName: execute.bal lineNumber: 81
			callableName: startSuite moduleName: ballerina.test.0 fileName: execute.bal lineNumber: 53
			callableName: __execute__ moduleName: intg_tests.dataproviders$test.0.tests.test_execute-generated_*****lineNumber: 27
		
		[pass] testDividingValuesWithBeforeFailing#0
		[pass] testDividingValuesWithBeforeFailing#1
		[pass] testDividingValuesWithBeforeFailing#3
		[pass] testDividingValuesWithBeforeFailing#4
		[pass] testExecutionOfBeforeFailing


		5 passing
		0 failing
		1 skipped

		Test execution time :*****s

	dataproviders.module1


		No tests found

		Test execution time :*****s

Generating Test Report
	data-providers/target/report/test_results.json

error: there are test failures